package user;

/**
* user/UserManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserManager.idl
* Thursday, June 13, 2019 8:40:00 AM CST
*/

public final class UserManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public user.UserManager value = null;

  public UserManagerHolder ()
  {
  }

  public UserManagerHolder (user.UserManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = user.UserManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    user.UserManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return user.UserManagerHelper.type ();
  }

}
