package user;


/**
* user/UserManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from UserManager.idl
* Thursday, June 13, 2019 8:40:00 AM CST
*/

public interface UserManager extends UserManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserManager
